./esbmc-wrapper.py -p ../sv-benchmarks/c/properties/unreach-call.prp -s kinduction --arch 64 ../sv-benchmarks/c/ldv-challenges/linux-3.14_complex_emg_linux-usb-dev_drivers-net-vmxnet3-vmxnet3.cil.i


--------------------------------------------------------------------------------


Verifying with ESBMC
Command: ./esbmc --no-div-by-zero-check --force-malloc-success --state-hashing --no-align-check --k-step 2 --floatbv --unlimited-k-steps ../sv-benchmarks/c/ldv-challenges/linux-3.14_complex_emg_linux-usb-dev_drivers-net-vmxnet3-vmxnet3.cil.i --64 --witness-output linux-3.14_complex_emg_linux-usb-dev_drivers-net-vmxnet3-vmxnet3.cil.i.graphml --no-pointer-check --no-bounds-check --interval-analysis --k-induction --max-inductive-step 3 

Function call to "c:linux-3.14_complex_emg_linux-usb-dev_drivers-net-vmxnet3-vmxnet3.cil.i@F@vmxnet3_get_drvinfo": number of arguments doesn't match type definition; some inconsistent rewriting occured


Unknown
